In [184]:
import pandas as pd
import numpy as np
## Create DF

df = (pd
        .DataFrame( index= pd.date_range( '2010-01-01', '2021-12-31' ,freq='3MS'))
      .reset_index()
      .rename(columns={'index' : 'y_dt'})
      .assign(key=1)
     )

## load data from Jennifer
df_to_merge = pd.read_csv('acs_pca_with_year_ratechange.csv')
df_to_merge = df_to_merge.drop('Unnamed: 0', axis=1)

df_census_tract = df_to_merge.loc[:, ['Zip Code']].drop_duplicates().assign(key=1)

df = pd.merge( df, df_census_tract, how='outer', on='key').drop(['key'], axis=1)

assert df_to_merge.shape[0] == df_to_merge.loc[:, ['Zip Code', 'Year']].drop_duplicates().shape[0]

## Deal with assert
df_to_merge.loc[:, 'y_dt'] = pd.to_datetime(df_to_merge['Year'], format='%Y')
df_to_merge = df_to_merge.sort_values('y_dt')

In [185]:
print(df_to_merge.shape[0])
print(df_to_merge.loc[:, ['Zip Code', 'Year']].drop_duplicates().shape[0])

18955
18955

In [186]:
df_to_merge

,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,Year,Zip Code,y_dt
0,0.523150,0.766194,0.164807,0.016885,0.005548,-0.004045,0.213682,-0.003381,0.005498,0.008814,2011.0,88430.0,2011-01-01
1287,0.520370,0.735813,-0.050542,0.000938,0.001051,-0.005299,0.005088,-0.012594,-0.000010,0.007796,2011.0,88063.0,2011-01-01
1286,0.520029,0.174482,-0.075442,0.000045,-0.004044,0.005332,-0.091560,-0.010035,0.001540,0.006854,2011.0,79942.0,2011-01-01
1285,0.520370,0.174420,-0.057450,-0.000762,0.001196,-0.001471,-0.012315,-0.009630,-0.005544,0.004594,2011.0,79938.0,2011-01-01
1284,0.520556,0.174891,-0.026460,0.000991,0.000990,-0.000748,0.006570,-0.003767,-0.003423,0.000918,2011.0,79936.0,2011-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17678,-0.479806,0.148445,-0.006891,0.016442,0.010047,-0.003757,-0.000154,0.000681,-0.001824,-0.001645,2021.0,79544.0,2021-01-01
17677,-0.479046,0.147934,-0.007198,-0.021095,0.010364,-0.039382,0.002785,0.000819,-0.001883,-0.002509,2021.0,79543.0,2021-01-01
17676,-0.479320,0.148111,-0.006454,-0.000629,-0.005112,0.020148,0.001462,0.006469,-0.001891,-0.006391,2021.0,79541.0,2021-01-01
17688,-0.480066,0.149560,-0.006093,0.023766,0.008609,0.005818,-0.000268,0.001223,-0.003025,-0.006448,2021.0,79562.0,2021-01-01
18954,-0.479375,-0.136329,-0.002775,-0.003121,0.000949,0.002400,0.003207,0.002686,-0.001773,-0.004628,2021.0,75420.0,2021-01-01

In [187]:
df.y_dt.sort_values().value_counts()

2010-01-01    1928
2010-04-01    1928
2016-07-01    1928
2016-10-01    1928
2017-01-01    1928
2017-04-01    1928
2017-07-01    1928
2017-10-01    1928
2018-01-01    1928
2018-04-01    1928
2018-07-01    1928
2018-10-01    1928
2019-01-01    1928
2019-04-01    1928
2019-07-01    1928
2019-10-01    1928
2020-01-01    1928
2020-04-01    1928
2020-07-01    1928
2020-10-01    1928
2021-01-01    1928
2021-04-01    1928
2021-07-01    1928
2016-04-01    1928
2016-01-01    1928
2015-10-01    1928
2012-10-01    1928
2010-07-01    1928
2010-10-01    1928
2011-01-01    1928
2011-04-01    1928
2011-07-01    1928
2011-10-01    1928
2012-01-01    1928
2012-04-01    1928
2012-07-01    1928
2013-01-01    1928
2015-07-01    1928
2013-04-01    1928
2013-07-01    1928
2013-10-01    1928
2014-01-01    1928
2014-04-01    1928
2014-07-01    1928
2014-10-01    1928
2015-01-01    1928
2015-04-01    1928
2021-10-01    1928
Name: y_dt, dtype: int64

In [188]:
df_to_merge.head()
merged_df = pd.merge( df, df_to_merge, how='left', on = ['y_dt', 'Zip Code'])

In [189]:
merged_df

,y_dt,Zip Code,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,Year
0,2010-01-01,88430.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2010-01-01,76542.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2010-01-01,76543.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010-01-01,76544.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2010-01-01,76548.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
92539,2021-10-01,77342.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92540,2021-10-01,76523.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92541,2021-10-01,77507.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92542,2021-10-01,77440.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92543,2021-10-01,76874.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [196]:
merged_df = merged_df.sort_values(['Zip Code', 'y_dt'])

new_df = merged_df.copy()
new_df.loc[:, 'new_col'] = np.nan

for census_tract in merged_df.loc[:, 'Zip Code'].unique():

    merged_df = merged_df.sort_values(['Zip Code', 'y_dt'])

    for col in ['PC1', 'PC2', 'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8', 'PC9', 'PC10']:


#         temp_df = (merged_df.loc[(merged_df.loc[:, 'Zip Code'] == census_tract), [col]]
#                     .interpolate(method='linear')
#                     .interpolate(method='bfill')
#                     .reset_index(drop=True))

        temp_df = (merged_df.loc[(merged_df.loc[:, 'Zip Code'] == census_tract), [col]]
                    .interpolate(method = "linear", order = 1,  limit_direction = "both",  downcast = "infer")
                    .interpolate(method='bfill')
                    .reset_index(drop=True))
        
        new_df.loc[(new_df.loc[:, 'Zip Code'] == census_tract), f'Quarterly {col}'] = temp_df.values

In [197]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 92544 entries, 631 to 90616
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   y_dt            92544 non-null  datetime64[ns]
 1   Zip Code        92544 non-null  float64
 2   PC1             18955 non-null  float64
 3   PC2             18955 non-null  float64
 4   PC3             18955 non-null  float64
 5   PC4             18955 non-null  float64
 6   PC5             18955 non-null  float64
 7   PC6             18955 non-null  float64
 8   PC7             18955 non-null  float64
 9   PC8             18955 non-null  float64
 10  PC9             18955 non-null  float64
 11  PC10            18955 non-null  float64
 12  Year            18955 non-null  float64
 13  new_col         0 non-null      float64
 14  Quarterly PC1   92544 non-null  float64
 15  Quarterly PC2   92544 non-null  float64
 16  Quarterly PC3   92544 non-null  float64
 17  Quarterly PC4   92544 non-null  float64
 18  Quarterly PC5   92544 non-null  float64
 19  Quarterly PC6   92544 non-null  float64
 20  Quarterly PC7   92544 non-null  float64
 21  Quarterly PC8   92544 non-null  float64
 22  Quarterly PC9   92544 non-null  float64
 23  Quarterly PC10  92544 non-null  float64
dtypes: datetime64[ns](1), float64(23)
memory usage: 17.7 MB

In [198]:
new_df = new_df.drop(columns=['new_col','Year', 'PC1', 'PC2', 'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8', 'PC9', 'PC10'])
# new_df.iloc[:, 2:8] = new_df.iloc[:, 2:11].astype(int)

In [199]:
new_df.shape

(92544, 12)

In [200]:
new_df.tail(30)

,y_dt,Zip Code,Quarterly PC1,Quarterly PC2,Quarterly PC3,Quarterly PC4,Quarterly PC5,Quarterly PC6,Quarterly PC7,Quarterly PC8,Quarterly PC9,Quarterly PC10
34704,2014-07-01,88430.0,0.170363,0.761295,-0.037718,-0.005095,0.000306,-0.006722,-0.023537,-0.008199,-0.000680,0.000732
36632,2014-10-01,88430.0,0.145314,0.761044,-0.053781,-0.005764,0.000176,-0.006864,-0.029612,-0.007932,-0.000947,0.000032
38560,2015-01-01,88430.0,0.120264,0.760793,-0.069843,-0.006434,0.000047,-0.007006,-0.035688,-0.007666,-0.001213,-0.000668
40488,2015-04-01,88430.0,0.095317,0.760709,-0.077473,-0.005819,0.000238,-0.007049,-0.028100,-0.008186,-0.000978,-0.000597
42416,2015-07-01,88430.0,0.070370,0.760626,-0.085102,-0.005205,0.000430,-0.007092,-0.020511,-0.008707,-0.000743,-0.000527
44344,2015-10-01,88430.0,0.045422,0.760542,-0.092732,-0.004590,0.000621,-0.007134,-0.012922,-0.009228,-0.000508,-0.000456
46272,2016-01-01,88430.0,0.020475,0.760458,-0.100362,-0.003976,0.000813,-0.007177,-0.005334,-0.009749,-0.000273,-0.000386
48200,2016-04-01,88430.0,-0.004491,0.760785,-0.078753,-0.004554,-0.000052,-0.006468,-0.004210,-0.008344,-0.000235,-0.000436
50128,2016-07-01,88430.0,-0.029458,0.761112,-0.057145,-0.005132,-0.000916,-0.005758,-0.003086,-0.006940,-0.000197,-0.000486
52056,2016-10-01,88430.0,-0.054425,0.761439,-0.035536,-0.005710,-0.001781,-0.005049,-0.001963,-0.005535,-0.000159,-0.000536
53984,2017-01-01,88430.0,-0.079392,0.761766,-0.013927,-0.006287,-0.002646,-0.004340,-0.000839,-0.004131,-0.000120,-0.000586
55912,2017-04-01,88430.0,-0.104265,0.761327,-0.014429,0.007280,-0.078588,-0.057008,-0.000178,-0.002902,-0.002192,-0.000474
57840,2017-07-01,88430.0,-0.129139,0.760887,-0.014930,0.020847,-0.154531,-0.109677,0.000484,-0.001673,-0.004264,-0.000362
59768,2017-10-01,88430.0,-0.154013,0.760448,-0.015431,0.034414,-0.230474,-0.162345,0.001145,-0.000444,-0.006335,-0.000249
61696,2018-01-01,88430.0,-0.178887,0.760008,-0.015933,0.047982,-0.306417,-0.215014,0.001807,0.000785,-0.008407,-0.000137
63624,2018-04-01,88430.0,-0.204006,0.760459,-0.015427,0.037457,-0.228261,-0.163975,0.001060,0.000259,-0.006430,-0.000827
65552,2018-07-01,88430.0,-0.229125,0.760910,-0.014921,0.026932,-0.150105,-0.112935,0.000312,-0.000266,-0.004453,-0.001517
67480,2018-10-01,88430.0,-0.254243,0.761362,-0.014415,0.016408,-0.071950,-0.061896,-0.000435,-0.000791,-0.002475,-0.002208
69408,2019-01-01,88430.0,-0.279362,0.761813,-0.013909,0.005883,0.006206,-0.010857,-0.001182,-0.001317,-0.000498,-0.002898
71336,2019-04-01,88430.0,-0.304281,0.761781,-0.014195,-0.000447,0.005826,-0.014791,-0.000728,-0.001162,-0.000259,-0.002840
73264,2019-07-01,88430.0,-0.329199,0.761749,-0.014481,-0.006778,0.005446,-0.018725,-0.000274,-0.001006,-0.000019,-0.002781
75192,2019-10-01,88430.0,-0.354118,0.761717,-0.014767,-0.013108,0.005066,-0.022659,0.000181,-0.000851,0.000220,-0.002723
77120,2020-01-01,88430.0,-0.379036,0.761686,-0.015053,-0.019438,0.004686,-0.026593,0.000635,-0.000696,0.000460,-0.002664
79048,2020-04-01,88430.0,-0.405163,0.762538,-0.015062,0.035619,-0.020184,0.091172,-0.003599,0.000171,-0.000178,-0.006730
80976,2020-07-01,88430.0,-0.431291,0.763391,-0.015071,0.090677,-0.045053,0.208937,-0.007833,0.001038,-0.000816,-0.010795
82904,2020-10-01,88430.0,-0.457418,0.764244,-0.015080,0.145735,-0.069923,0.326702,-0.012066,0.001905,-0.001453,-0.014861
84832,2021-01-01,88430.0,-0.483545,0.765097,-0.015089,0.200793,-0.094792,0.444467,-0.016300,0.002772,-0.002091,-0.018927
86760,2021-04-01,88430.0,-0.483545,0.765097,-0.015089,0.200793,-0.094792,0.444467,-0.016300,0.002772,-0.002091,-0.018927
88688,2021-07-01,88430.0,-0.483545,0.765097,-0.015089,0.200793,-0.094792,0.444467,-0.016300,0.002772,-0.002091,-0.018927
90616,2021-10-01,88430.0,-0.483545,0.765097,-0.015089,0.200793,-0.094792,0.444467,-0.016300,0.002772,-0.002091,-0.018927

In [201]:
new_df.to_csv('pca_interpolated_ratechange.csv')